module.exports = {
	ABOUT_CLUB: 'ABOUT_CLUB',
	TAEKWONDO: 'TAEKWONDO',
	HAPKIDO: 'HAPKIDO',
	JUJUTSU: 'JUJUTSU',
	MUAY_THAI: 'MUAY_THAI',
	SELF_DEFENSE: 'SELF_DEFENSE',
	SCHEDULE: 'SCHEDULE',
	MEM_PRICING: 'MEM_PRICING'
};
