module.exports = {
  TAEKWONDO: 'TAEKWONDO',
  HAPKIDO: 'HAPKIDO',
  JUJUTSU: 'JUJUTSU',
  MUAY_THIA: 'MUAY_THAI',
  SELF_DEFENSE: 'SELF_DEFENSE',
  SCHEDULE: 'SCHEDULE',
  MEM_PRICING: 'MEM_PRICING'
};
